### ISSUE TITLE
Feedbacks 

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/TBML#3]
> We assert that a descriptive language which we name TBML is needed to provide a pathway from blockchain technologies, most prominently Ethereum, to allowing blockchain to perform the two major functions: "Frictionless Market" and "Integrate the web

".

May not be a good idea of highlighting Ethereum

**Comment by colourful-land** [comment]
Edited out by JS a while ago. But still Ethereum is mentioned multiple times.

P.S. Use "May not be a good idea of highlighting Ethereum" as the issue title. You are naming an issue feedback. It's like naming a bug "found a bug".
