### ISSUE TITLE
Need an "official" definition of TokenScript

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/TBML#33]
Like:
**Hypertext Markup Language (HTML)** is the standard markup language for creating web pages and web applications. With Cascading Style Sheets (CSS) and JavaScript, it forms a triad of cornerstone technologies for the World Wide Web.
Web browsers receive HTML documents from a web server or from local storage and render the documents into multimedia web pages. HTML describes the structure of a web page semantically and originally included cues for the appearance of the document.

**JavaScript** often abbreviated as JS, is a high-level, interpreted programming language that conforms to the ECMAScript specification. It is a programming language that is characterized as dynamic, weakly typed, prototype-based and multi-paradigm.
Alongside HTML and CSS, JavaScript is one of the core technologies of the World Wide Web. JavaScript enables interactive web pages and is an essential part of web applications. The vast majority of websites use it, and major web browsers have a dedicated JavaScript engine to execute it.

definition + utility + a little bit how to "write" it(like if you know HTML and javascript, you can easy use it)

**Comment by zhangzhongnan928** [comment]
https://github.com/AlphaWallet/TBML/pull/41

**Comment by colourful-land** [comment]
> #41

Instead of referring to PR in issue, please refer to issue in PR. Github set the rule.

**Comment by colourful-land** [comment]
I moved your definition.md content to README.md you can see it here:

https://github.com/AlphaWallet/Tokenscript/blob/master/README.md

**Comment by dtbx** [comment]
Hey @zhangzhongnan928 , Suggestion for a small edit:

Change from: 
TokenScript Project is an opensource and NFP project, the goal to develop and help with adoption of TokenScript, the standard markup language for creating and using cryptographic tokens(e.g. blockchain tokens) and DApps.

To:
TokenScript is a standard markup language built to creating and using cryptographic tokenized assets (e.g. blockchain tokens) and DApps.

Better not discuss NFP and other forms of governance that are not certain at this stage and add unnecessary scrutiny. Generally suggest to shorten a lot these kind of documents. Will DM :)
